### ISSUE TITLE
Parent

### ISSUE THREAD

**Issue by ioRekz** [clj-commons/hickory#23]
Is there a way to do like a jquery .parent() ?

**Comment by davidsantiago** [comment]
I don't know jquery. What does that do?

**Comment by ioRekz** [comment]
Of course. When selecting a node in the tree. You can call parent on it and get its parent.

**Comment by davidsantiago** [comment]
Oh, OK, I see. You can absolutely do this. 

Normally the select function returns a list of nodes, but you can also get a list of zipper-locs instead. You can do that by calling [select-locs](http://davidsantiago.github.io/hickory/hickory.select.html#var-select-locs) instead of select. Then each item in the vector that is returned by select-locs will be a zipper, usable with all of the tree navigation functions of clojure.zip. So you'd call select-locs, instead of select, and then use clojure.zip/up on each of those to get their parents. As with any zipper, you'd want to call clojure.zip/node to get the node that you can examine before looking at it.

**Comment by vspinu** [comment]
Any news on this?   You can do all other directions, `child`, `follow` and `precede`, but not `parent`.  So you can currently get both A and C in (A B C) but only C in (A (B (C))).

**Comment by davidsantiago** [comment]
Are you asking about a selector function? Doesn't the has-child selector do what you want?

**Comment by vspinu** [comment]
Right. That's exactly what I was looking for. Don't understand how I missed it in the docs. Thanks!!!
